circle ci stuff

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,28 +1,14 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
 commands:
   failure:
-    description: Retry a step when it fails
-    parameters:
-      repo:
-        type: string
-        default: ""
-      when:
-        type: string
-        default: "on_fail"
-
+    description: Notify failure
     steps:
       - run:
           command: |
-            echo "This ran because the previous step failed"
-            echo "<<parameters.when>>"
-          name: step due to failure
-          when: <<parameters.when>>
+            echo "One of the previous jobs failed."
+          name: Failure Notification
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
 jobs:
   test-backend:
     docker:
@@ -32,11 +18,10 @@ jobs:
       - run:
           name: "Test backend"
           command: "echo Testing backend"
-      # # Force a failure
-      # - run: exit 1
-      # - failure:
-      #     repo: "TEST"
-      #     when: "on_fail"
+      - run:
+          name: "Force failure (for testing)"
+          command: "exit 1" # You can remove this once testing is done
+
   test-frontend:
     docker:
       - image: cimg/base:current
@@ -45,6 +30,7 @@ jobs:
       - run:
           name: "Test frontend"
           command: "echo Testing frontend"
+
   system-checks:
     docker:
       - image: cimg/base:current
@@ -58,7 +44,7 @@ jobs:
     docker:
       - image: cimg/base:current
     steps:
-      - run: "echo Failure of the setup stage"
+      - failure
 
   dev-build:
     docker:
@@ -114,8 +100,6 @@ jobs:
           name: "Test prod deploy"
           command: "echo Testing prod deploy"
 
-# Orchestrate jobs using workflows
-# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
 workflows:
   dev-staging-prod-single-workflow:
     jobs:
@@ -123,7 +107,7 @@ workflows:
       - test-frontend
       - system-checks
 
-      # Success path if all tests and system checks pass
+      # Success path if all tests pass
       - dev-build:
           requires:
             - test-backend
@@ -133,15 +117,18 @@ workflows:
           requires:
             - dev-build
 
-      # Failure path if any of the tests or system checks fail
+      # Failure path: Run if any of the tests or system checks fail
       - setup-failure:
           requires:
             - test-backend
             - test-frontend
             - system-checks
-          when: on_fail
+          filters:
+            branches:
+              only:
+                - master # Adjust this based on your use case
 
-      # Success path if dev-deploy passes
+      # Continue with the next stages if deployment to dev passes
       - staging-build:
           requires:
             - dev-deploy
@@ -149,7 +136,7 @@ workflows:
           requires:
             - staging-build
 
-      # Success path if staging-deploy passes
+      # Approval before moving to production
       - prod-build:
           type: approval
           requires:
