trying to access env vars in different jobs

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,43 +94,42 @@ jobs:
           command: echo "Running failure steps because dev deploy failed. This would be a good place to send a notification with details to slack."
 
   # STAGING DEPLOYMENT JOBS
-  staging-build:
-    docker:
-      - image: cimg/base:current
-    steps:
-      - checkout
-      - attach_workspace:
-          at: ~/
-      - run:
-          name: "Load branch and commit information"
-          command: |
-            source ~/env_vars.sh
-            echo "Branch: $BRANCH"
-            echo "Current Commit: $CURRENT_COMMIT"
-            echo "Last Commit: $LAST_COMMIT"
-      - run:
-          name: "Test staging build"
-          command: |
-            "echo Testing staging build"
-            # Simulate a failure (you can remove this line)
-            false || (echo "Backend test failed! Performing alternative action..." && exit 1)
-      - run:
-          name: "Run on staging build failure"
-          when: on_fail
-          command: |
-            echo "Staging build failed. Rolling back dev deployment..."
-            echo "Rolling back to commit: $LAST_COMMIT"
-            git reset --hard $LAST_COMMIT
-      - run:
-          name: "Rerun dev-build and dev-deploy"
-          when: on_fail
-          command: |
-            echo "Rerunning dev-build and dev-deploy with commit $LAST_COMMIT"
-            curl -u ${CIRCLECI_API_TOKEN}: \
-              -d build_parameters[CIRCLE_JOB]=dev-build \
-              -d build_parameters[CIRCLE_JOB]=dev-deploy \
-              https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/tree/:branch
-                
+    staging-build:
+      docker:
+        - image: cimg/base:current
+      steps:
+        - checkout
+        - attach_workspace:
+            at: ~/
+        - run:
+            name: "Load branch and commit information"
+            command: |
+              source ~/env_vars.sh
+              echo "Branch: $BRANCH"
+              echo "Current Commit: $CURRENT_COMMIT"
+              echo "Last Commit: $LAST_COMMIT"
+        - run:
+            name: "Test staging build"
+            command: |
+              echo "Testing staging build"
+              # Simulate a failure (you can remove this line)
+              false || (echo "Backend test failed! Performing alternative action..." && exit 1)
+        - run:
+            name: "Run on staging build failure"
+            when: on_fail
+            command: |
+              echo "Staging build failed. Rolling back dev deployment..."
+              echo "Rolling back to commit: $LAST_COMMIT"
+              git reset --hard $LAST_COMMIT
+        - run:
+            name: "Rerun dev-build and dev-deploy"
+            when: on_fail
+            command: |
+              echo "Rerunning dev-build and dev-deploy with commit $LAST_COMMIT"
+              curl -u ${CIRCLECI_API_TOKEN}: \
+                -d build_parameters[CIRCLE_JOB]=dev-build \
+                -d build_parameters[CIRCLE_JOB]=dev-deploy \
+                https://circleci.com/api/v1.1/project/:vcs-type/:username/:project/tree/:branch
     docker:
       - image: cimg/base:current
     steps:
